INSERT INTO ROLES (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('ADMIN', 'The administrator role');

INSERT INTO USERS (EMAIL, CONFIRMED, FAILED_ATTEMPTS, PASSWORD_HASH, JAMES_PASSWORD_HASH, PASSWORD_SALT, USERNAME, UPDATED) VALUES ('admin@rhex.us', true, 0, '3bfc3a77980fc82fce8d486a29c0eb088195194e2b4415e7c0ad3127996ffac4', '9djPJw6Cz/ASurswYxn/oTmD', 469722569, 'admin', NOW());

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) SELECT u.USER_ID, r.ROLE_ID FROM USERS u, ROLES r WHERE u.USERNAME = 'admin' and r.ROLE_NAME = 'ADMIN';